export const GENRES_DATA = [
  { name: "Фантастика", slug: "sci-fi" },
  { name: "Драма", slug: "drama" },
  { name: "Бойовик", slug: "action" },
  { name: "Комедія", slug: "comedy" },
  { name: "Трилер", slug: "thriller" },
  { name: "Кримінал", slug: "crime" },
  { name: "Мелодрама", slug: "romance" },
  { name: "Анімація", slug: "animation" },
  { name: "Пригоди", slug: "adventure" },
  { name: "Вестерн", slug: "western" },
  { name: "Фентезі", slug: "fantasy" },
];

export const MOVIES_DATA = [
  {
    title: "Інтерстеллар",
    year: 2014,
    rating: 8.7,
    posterUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    description: "Команда дослідників подорожує через червоточину в космосі, намагаючись знайти нову домівку для людства.",
    trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
    cast: ["Меттью Макконахі", "Енн Гетевей", "Джессіка Честейн", "Майкл Кейн"],
    genres: ["Фантастика", "Драма"],
  },
  {
    title: "Втеча з Шоушенка",
    year: 1994,
    rating: 9.3,
    posterUrl: "https://image.tmdb.org/t/p/w500/9cjIGRQL0PQa0JUbMQfzFliGEGR.jpg",
    description: "Банкір Енді Дюфрейн, засуджений за вбивство дружини та її коханця, потрапляє до в'язниці Шоушенк.",
    trailerUrl: "https://www.youtube.com/embed/6hB3S9d6pV4",
    cast: ["Тім Роббінс", "Морган Фріман", "Боб Гантон", "Кленсі Браун"],
    genres: ["Драма"],
  },
  {
    title: "Темний лицар",
    year: 2008,
    rating: 9.0,
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgMe1nNaD3.jpg",
    description: "Бетмен, лейтенант Гордон та прокурор Гарві Дент об'єднують зусилля проти злочинності в Готемі.",
    trailerUrl: "https://www.youtube.com/embed/EXeTwQWrcwY",
    cast: ["Крістіан Бейл", "Хіт Леджер", "Аарон Екхарт", "Гері Олдман"],
    genres: ["Бойовик", "Драма", "Кримінал"],
  },
  {
    title: "Початок",
    year: 2010,
    rating: 8.8,
    posterUrl: "https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
    description: "Дом Кобб — досвідчений злодій, який спеціалізується на вилученні секретів з підсвідомості людей під час сну.",
    trailerUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
    cast: ["Леонардо ДіКапріо", "Джозеф Гордон-Левітт", "Елліот Пейдж", "Том Гарді"],
    genres: ["Фантастика", "Бойовик", "Трилер"],
  },
  {
    title: "Форрест Гамп",
    year: 1994,
    rating: 8.8,
    posterUrl: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    description: "Історія простого хлопця з Алабами, який випадково стає свідком та учасником ключових подій американської історії.",
    trailerUrl: "https://www.youtube.com/embed/bLvqoHBptjg",
    cast: ["Том Генкс", "Робін Райт", "Гері Сініз", "Саллі Філд"],
    genres: ["Драма", "Комедія", "Мелодрама"],
  },
  {
    title: "Матриця",
    year: 1999,
    rating: 8.7,
    posterUrl: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    description: "Програміст Томас Андерсон дізнається, що реальність — це симуляція, створена машинами.",
    trailerUrl: "https://www.youtube.com/embed/vKQi3bBA1y8",
    cast: ["Кіану Рівз", "Лоренс Фішберн", "Керрі-Енн Мосс", "Г'юго Вівінг"],
    genres: ["Фантастика", "Бойовик"],
  },
  {
    title: "Бійцівський клуб",
    year: 1999,
    rating: 8.8,
    posterUrl: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    description: "Офісний працівник зустрічає харизматичного Тайлера Дердена. Разом вони створюють підпільний бійцівський клуб.",
    trailerUrl: "https://www.youtube.com/embed/qtRKdVHc-cE",
    cast: ["Бред Пітт", "Едвард Нортон", "Гелена Бонем Картер"],
    genres: ["Драма", "Трилер"],
  },
  {
    title: "Побачення наосліп",
    year: 2023,
    rating: 7.2,
    posterUrl: "https://image.tmdb.org/t/p/w500/aGBuiirBIQ7o64FmJxO53eYDuro.jpg",
    description: "Двоє незнайомців погоджуються на побачення наосліп, не підозрюючи, наскільки різними виявляться їхні очікування.",
    trailerUrl: "https://www.youtube.com/embed/ZTCQyljnBbg",
    cast: ["Люсі Гейл", "Томас Манн"],
    genres: ["Комедія", "Мелодрама"],
  },
  {
    title: "Паразити",
    year: 2019,
    rating: 8.5,
    posterUrl: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    description: "Бідна сім'я Кім поступово проникає в розкішний дім багатої родини Пак.",
    trailerUrl: "https://www.youtube.com/embed/5xH0HfJHsaY",
    cast: ["Сон Кан-хо", "Лі Сон-гюн", "Чо Є-чжон", "Чхве У-шик"],
    genres: ["Трилер", "Драма", "Комедія"],
  },
  {
    title: "Джокер",
    year: 2019,
    rating: 8.4,
    posterUrl: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    description: "Артур Флек — невдалий стендап-комік, якого суспільство відкидає. Поступово він перетворюється на Джокера.",
    trailerUrl: "https://www.youtube.com/embed/zAGVQLHvwOY",
    cast: ["Хоакін Фенікс", "Роберт Де Ніро", "Зазі Бітц", "Френсіс Конрой"],
    genres: ["Драма", "Трилер", "Кримінал"],
  },
  {
    title: "Вгору",
    year: 2009,
    rating: 8.3,
    posterUrl: "https://image.tmdb.org/t/p/w500/mOrtu9pbQ0UShAdBs8M6YA2kJG4.jpg",
    description: "78-річний Карл Фредріксен прив'язує до будинку тисячі повітряних кульок і вирушає в подорож.",
    trailerUrl: "https://www.youtube.com/embed/pkqzFUhGPJg",
    cast: ["Ед Еснер", "Джордан Нагаї", "Боб Петерсон", "Крістофер Пламмер"],
    genres: ["Анімація", "Пригоди", "Комедія"],
  },
  {
    title: "Зоряні війни: Нова надія",
    year: 1977,
    rating: 8.6,
    posterUrl: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    description: "Молодий фермер Люк Скайвокер приєднується до повстанців, щоб врятувати принцесу Лею.",
    trailerUrl: "https://www.youtube.com/embed/vZ734NWnAHA",
    cast: ["Марк Гемілл", "Гаррісон Форд", "Керрі Фішер", "Алек Гіннесс"],
    genres: ["Фантастика", "Пригоди"],
  },
  {
    title: "Славні хлопці",
    year: 1990,
    rating: 8.7,
    posterUrl: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    description: "Історія злету та падіння мафіозі Генрі Гілла, від захопленого підлітка до інформатора ФБР.",
    trailerUrl: "https://www.youtube.com/embed/qo5jJpHtI1Y",
    cast: ["Рей Ліотта", "Роберт Де Ніро", "Джо Пеші", "Лоррейн Бракко"],
    genres: ["Кримінал", "Драма"],
  },
  {
    title: "Вічне сяйво чистого розуму",
    year: 2004,
    rating: 8.3,
    posterUrl: "https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
    description: "Після розставання Джоел та Клементайн вирішують стерти спогади один про одного.",
    trailerUrl: "https://www.youtube.com/embed/07-QBnEkgXU",
    cast: ["Джим Керрі", "Кейт Вінслет", "Кірстен Данст", "Марк Раффало"],
    genres: ["Драма", "Мелодрама", "Фантастика"],
  },
  {
    title: "Дюна",
    year: 2021,
    rating: 8.0,
    posterUrl: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    description: "Пол Атрейдес вирушає на найнебезпечнішу планету у Всесвіті — Арракіс.",
    trailerUrl: "https://www.youtube.com/embed/n9xhJrPXop4",
    cast: ["Тімоті Шаламе", "Ребекка Фергюсон", "Оскар Айзек", "Зендея"],
    genres: ["Фантастика", "Пригоди", "Драма"],
  },
  {
    title: "Джанго вільний",
    year: 2012,
    rating: 8.4,
    posterUrl: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
    description: "Звільнений раб Джанго об'єднується з мисливцем за головами, щоб врятувати дружину.",
    trailerUrl: "https://www.youtube.com/embed/0fUCuvNlOCg",
    cast: ["Джеймі Фокс", "Крістоф Вальц", "Леонардо ДіКапріо", "Семюел Л. Джексон"],
    genres: ["Вестерн", "Драма", "Бойовик"],
  },
  {
    title: "Одного разу в Голлівуді",
    year: 2019,
    rating: 7.6,
    posterUrl: "https://image.tmdb.org/t/p/w500/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
    description: "Лос-Анджелес, 1969. Актор Рік Далтон та його дублер намагаються знайти своє місце в Голлівуді.",
    trailerUrl: "https://www.youtube.com/embed/ELeMaP8SGJA",
    cast: ["Леонардо ДіКапріо", "Бред Пітт", "Марго Роббі", "Ел Пачіно"],
    genres: ["Комедія", "Драма"],
  },
  {
    title: "Гравітація",
    year: 2013,
    rating: 7.7,
    posterUrl: "https://image.tmdb.org/t/p/w500/kZ2nZw8dp0v0MwjEyMVZBkPkYMv.jpg",
    description: "Астронавт Раян Стоун залишається одна в космосі після катастрофи з уламками супутника.",
    trailerUrl: "https://www.youtube.com/embed/OiTiKOy59o4",
    cast: ["Сандра Буллок", "Джордж Клуні"],
    genres: ["Фантастика", "Трилер"],
  },
  {
    title: "Король Лев",
    year: 1994,
    rating: 8.5,
    posterUrl: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    description: "Молодий левеня Сімба тікає зі свого королівства після загибелі батька.",
    trailerUrl: "https://www.youtube.com/embed/4sj1MT05lAA",
    cast: ["Метью Бродерік", "Джеремі Айронс", "Джеймс Ерл Джонс", "Натан Лейн"],
    genres: ["Анімація", "Пригоди", "Драма"],
  },
  {
    title: "Зелена миля",
    year: 1999,
    rating: 8.6,
    posterUrl: "https://image.tmdb.org/t/p/w500/o0lO84GI7qrG6XkLB23jlB8cMb4.jpg",
    description: "Наглядач тюремного блоку смертників зустрічає незвичайного в'язня Джона Коффі з надприродним даром.",
    trailerUrl: "https://www.youtube.com/embed/Ki4haFrqSrw",
    cast: ["Том Генкс", "Майкл Кларк Дункан", "Девід Морс", "Сем Роквелл"],
    genres: ["Драма", "Фентезі", "Кримінал"],
  },
];
